### ISSUE TITLE
物理演算パッケージについて

### ISSUE THREAD

**Issue by biwamin** [tessai9/ghost_house_vr#31]
feature/install_aframe_physics_systemとaframe-extrasを用い、playerと壁の衝突判定を実装したが、以下の問題点があった。

・plyer側に指定しているkinematic-bodyとstatic-bodyのあたり判定の使用がわからない。
・インスペクターで表示するとkinematic-bodyを指定したplayerが床を突き抜けて落ち続ける
・落下速度がおかしい
・結局ammoを用いることができずに、cannonを用いることになった

今後の方針案：
１．aframe_physics_systemのammo driverとammo APIを使ってplayerのあたり判定を自作する
２．ammo.jsを用いて、衝突判定を自作する
３．今後参考になるサンプルが見つかるまでそのまま

一旦はこのままで他のことやりつつでよいかも

**Comment by tessai9** [comment]
ammo.jsを使った衝突判定は[ここ](https://forum.babylonjs.com/t/wall-collision-ammo-js/2701)が参考になるかも？

ただ、結構ハマりポイントになりそうなんで一旦はこのままで進めていこうか

**Comment by biwamin** [comment]
レイキャスター検証中

**Comment by tessai9** [comment]
raycasterで実装する方針に決定したのでclose
